---
title: Shiny App Self-Review
author: Brendi Ang
date: '2020-10-15'
slug: shiny-app-self-review
categories:
  - R
tags:
  - R Markdown
subtitle: ''
summary: ''
authors: []
lastmod: '2020-10-15T12:31:07+11:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

# Introduction

## The Shiny App

The interactive web application was created to provide key data visualisations and allow users to explore Covid-19 cases across the U.S states. The interactive features allow for a more personalised user experience, to explore as little or as much of the analysed data. In all tabs, the user can use the slider input and drop down list to manoeuvre between dates and states across the United States to visualise how the Covid-19 trajectories changes with these inputs.


## Functions of the Shiny App

### Tab 1: United States COVID-19 Cases (per 100,000) by State

[*Add video/image*]

<iframe width="560" height="315" src="../vid/tab1_example.mp4" frameborder="0" allowfullscreen></iframe>


The dataset for this component originates from the NY Times (*Reference*). 

This component provides the confirmed Covid-19 cases, per 100,000 population that were reported by the state on a given date (*Reference to NY Times*). The total confirmed cases is plotted on the U.S state map, and is made with a sequential colour scale to establish the geographical location in which the total confirmed cases are the highest. This trend is also plotted on a histogram on the side bar panel, as the pattern can be better articulated since people are generally better at comparing lengths on a common scale as compared to shading or colour saturations (@cleveland1984graphical).

As a case in point, it can be observed in this tab that after New York surpassed Washington on the 16th March 2020 in the total number of Covid-19 cases, they have since led the United States in this aspect up till this date.

### Tab 2: Positive Results in Covid-19 testing

The dataset for this component originates from the NY Times (*Reference*). Covid-19 testing promotes early detection of community-acquired Covid-19 cases, which can support in public health response to the pandemic such as the allocation of resources for the more vulnerable regions. 

This section consists of two components. The first tab measures the percentage of Covid-19 tests returning positive on a given date and is charted on the US state map. Correspondingly, the second segment then depicts the aggregated test results as of the chosen date selected by the user. 


# Self Review

## What was done well?

**Layout**
- Structure of the app was done well
  - Manually divided user interface (ui) into grids using `fluidRow`
  - Utilised tab panel to combine different tabs into a single panel

**Reactive Programming**
- Used observeEvent() to explicitly trigger an action when action button is clicked
- Added custom error message when no U.S. states are picked

## What are the points I can improve on?

**Debugging Process**
I could improve on the debugging process of the shiny app. The code execution wasn't as linear as the usual Rmd files I was accustomed to due to the reactive codes. For this assignment, I created a new Rmd file to make reference to when I ran into errors, which wasn't the best practice.

**Organise large data files to optimise speed of App**
  - Learn how to organise large data files in a shiny app to optimise performance
    - Data consisted of more than 2 million observations
    
**Adding new graph on top of map to better communicate results**
- In tab 2, map only shows geogrpahical location, users have to hover mouse to see which state does the trned correspond to.
- Adding graph (e.g. dot point or histogram (*Plot above to compare*)) would better articulate this/

## What are some things that you'd like to add that's plausible?

**Multiple reactive Expressions**
- Having more than one reactive expression 
  - e.g. In tab 1, when a state is clicked on the U.S state map, the bar plot will automatically update to these states instead of always having to refer to the select input.
  
*Cancel long-running tasks while loading*
- Due to the large amoung of data, it takes about 5 seconds or so to load when running locally.
  - Ability to cancel task when loading

*Pre-populate or download shiny input based on URL parameters*
- As the datasets are updated regularly, we may download directly from the source to provide a complete record of the ongoing outbreak.

## What are some things that you'd like that add but cannot be done yet due to limitation in data/technology?

**Limitation of data**
  - hospital vs deaths data (needed more data)
  - Reliability of the data (elaborate on errors - e.g. due to different state jurisdictions or reporting requirements)
  
**Limitation due to technology**
  - 
